### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by umaar** [AurousGroup/frontend#19]
Various parts of the UI don't work for me & I was wondering, is there a way to "Inspect" the app (e.g. inspect element)? That way I can discover if there's a JS error.

**Comment by NoShotz** [comment]
If it is the shuffle and replay buttons, then it isn't a problem because
they havnt been implemented from what I know

**Comment by umaar** [comment]
It was actually playing of audio that went funny, e.g. many tracks were in a "playing" state (since their icons changed to pause) but nothing was playing, & the UI went slightly unresponsive. I've restarted the app and now it's hanging on autoupdating (it's been about 15 minutes).

![screen shot 2015-10-13 at 15 58 49](https://cloud.githubusercontent.com/assets/381495/10458574/555e2628-71c3-11e5-9c29-de97333b659d.png)

**Comment by Codeusa** [comment]
Run Aurous-core.jar from command line and it will print out a remote debugging url for chrome. Aurous.me is down atm due to heavy load.

**Comment by umaar** [comment]
Ok makes sense. I see:

`java.io.IOException: Server returned HTTP response code: 522 for URL: https://aurous.me/updates/data/data/assets/css/partials/_loading.scss`

Could be worth cancelling the update process if resource downloading fails which would allow the app to run like normal.

**Comment by umaar** [comment]
Anyway, this ticket was about remote debugging which has been explained, good to know!
