### ISSUE TITLE
gulp stuck

### ISSUE THREAD

**Issue by udiNur** [AurousGroup/frontend#58]
hi
first, Sorry for my bad english

when i try to run 'npm install' i was get this:
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})

then i update node js. following this commands:
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node 
  
then i download  from here agen. and i run 'npm install'
output: http://gyazo.com/370090461fb20db3d495226f0bbc7247.png

for installing gulb i run 'sudo npm install --global gulp' 
and then i run 'gulb' and noting append 10 Minutes
http://gyazo.com/4acd84498da486cab054477751efc880.png

**Comment by srcnalt** [comment]
Well that actually happens to me too, but since it has converted scss to css I just quit it. Nothing goes wrong.

**Comment by udiNur** [comment]
@srcnalt 
this list  of css file in frontend/assets/css
main.css      main.scss  override-css.css   override-scss.css.map  partials/
main.css.map  modules/   override-scss.css  override-scss.scss     vendor/

what i need to do?

**Comment by srcnalt** [comment]
Just make your changes on main.scss or related file in partials folder. Then run gulp command in frontend folder. That will do it.

**Comment by udiNur** [comment]
thank you!
