### ISSUE TITLE
Some character sets not supported

### ISSUE THREAD

**Issue by RoxKilly** [AurousGroup/frontend#7]
This may be by design, or maybe even a fonts issue with my computer I don't know.

Search for `Alors on danse`, then scroll down and you'll notice that some titles show as gibberish. Seems some character sets are not supported.

Win 7 x64.  Unless the app will require auto-update to work, please think about surfacing the version number somewhere in the UI. It will make reporting bugs more effective.

**Comment by Nickforall** [comment]
This is probably not in your pc, doesn't look like non-latin character sets are supported here: [Fira.css](https://github.com/AurousGroup/frontend/blob/master/assets/fonts/fira.css)

**Comment by dmxt** [comment]
This issue is fixed. Please update Aurous.
